spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/kakaopay
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-timeout: 3000
    maximum-pool-size: 5